FROM node:alpine
WORKDIR '/app'
COPY ./package.json /.

RUN npm install

RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

COPY /. /.

CMD ["npm", "run", "build"]

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --FROM=builder /app/build /usr/share/nginx/html
